sonar.projectKey=Rodrig0496_proyecto-si784-2026-i-u2-analiz_est_de_cod_con_met
sonar.organization=rodrig0496
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=app/presentacion/static/examples/**
